version: '3.8'

services:
  searchservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=FastTechFoods
    depends_on:
      - mongodb
    networks:
      - fasttech-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb-search
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - fasttech-network

networks:
  fasttech-network:
    driver: bridge

volumes:
  mongodb_data: 